network:
  version: 2
  renderer: networkd

  ethernets:
      eno2:
          dhcp4: no

  wifis:
      wlo1:
          dhcp4: yes
          access-points:
              "SEU_SSID":
                  PASSWORD: "SUA_SENHA"
      bridges:
          br0:
              interfaces: [eno2]
              dhcp4: yes
