[db]
vm-db ansible_host=192.168.122.135

[docker]
vm-docker ansible_host=192.168.122.190

[http]
vm-http ansible_host=192.168.122.173

[app]
vm-app ansible_host=192.168.122.199

[monitoring]
vm-monitoring ansible_host=192.168.122.176

[all:vars]
ansible_user=devops
