- hosts: vm-db
  become: yes

  vars:
    db_name: appdb
    db_user: devops
    db_pass: devops123

  tasks:
    - name: install postgres
      apt:
        name: postgresql
        state: present
        update_cache: yes

    - name: start postgres
      systemd:
        name: postgresql
        state: started
        enabled: yes

    - name: create database
      become: true
      become_user: postgres
      community.postgresql.postgresql_db:
        name: minha_db

    - name: create user
      become: true
      become_user: postgres
      community.postgresql.postgresql_user:
        name: app_user
        password: "senha"
        state: present
