- hosts: vm-monitoring
  become: yes

  tasks:
    - name: run grafana container
      docker_container:
        name: grafana
        image: grafana/grafana
        state: started
        restart_policy: always
        ports:
          - "3000:3000"
