[all]
vm-docker
vm-db
vm-monitoring
vm-http
vm-app

[db]
vm-db

[docker]
vm-docker

[http]
vm-http

[infra]
vm-docker
vm-db
vm-monitoring

[app]
vm-http
vm-app

[monitoring]
vm-monitoring

[all:vars]
ansible_user=devops
